---
title: Timing for different methods to query vcf files
author: Gibran Hemani
date: 2/10/2019
---


Setup

```{r}
library(knitr)
opts_chunk$set(warning=FALSE, message=FALSE, cache=TRUE)
library(devtools)
load_all()
fn <- system.file("data","IEU-a-2.vcf.gz", package="gwasvcftools")
chrompos <- "20:800000-4000000"
pval <- 5e-8
rsid <- c("rs3128126", "rs3121561", "rs3813193")
```

Reading in the vcf file

```{r}
system.time({
	v <- readVcf(fn)
})
```

Different methods for searching for rsid:

```{r}
system.time({
	query_rsid_vcf(rsid, v)
})
system.time({
	query_rsid_file(rsid, fn)
})
system.time({
	query_rsid_bcftools(rsid, fn)
})
```

Different methods for searching by p-value:

```{r}
system.time({
	query_pval_vcf(pval, v)
})
system.time({
	query_pval_file(pval, fn)
})
system.time({
	query_pval_bcftools(pval, fn)
})
```

Different methods for searching by chrompos:

```{r}
system.time({
	query_chrompos_vcf(chrompos, v)
})
system.time({
	query_chrompos_file(chrompos, fn)
})
system.time({
	query_chrompos_bcftools(chrompos, fn)
})
```
